### ISSUE TITLE
would this review of a postmortem be appropriate?

### ISSUE THREAD

**Issue by kevinburkeshyp** [Operations-Incident-Board/Postmortem-Report-Reviews#3]
The SEC order to shut down Knight Capital: https://www.sec.gov/litigation/admin/2013/34-70694.pdf

Contains really useful information about what went wrong - it's also interesting that Knight's poor deployment practices can and did break the law

**Comment by gabinante** [comment]
Hi Kevin,

I think that the government document is itself a very interesting postmortem. I'd love to see a review of it in our Repo, but the document goes into a lot of detail on laws that were broken, etc... a lot of non-operational stuff that needs to be filtered out. Furthermore, it doesn't follow our review format (see readme).

If you want to take a stab at disseminating that document and write a report, that'd be awesome - please feel free to make a PR :) If not, someone else will probably tackle it in the coming weeks as it's a very interesting outage that definitely deserves a review.
